### PR TITLE
Added UK Colemak Mappings

### PR DESCRIPTION
**Pull request by nygellyndley**
Added UK Colemak Mappings
Have not built via remapper

### CODE REVIEW

**Comment by Hancho2009** [comment]
I think for the newest theCore release https://github.com/michaelnew/TheCoreConverter/ was used. I think you should make a pull request for that too.

**Comment by JaKaTaK** [comment]
I'll try to get that figured out this weekend.  I've forgotten hiw to do the git hub things since it's been a while

**Comment by Hancho2009** [comment]
JaKaTaK do you also want the changes michaelnew did merged back in your repo?

**Comment by nygellyndley** [comment]
This PR now contains all Michael's changes.  If it's merged it will bring this repo bang up to date.

Or alternatively I can close this down and michael's can be the primary repo for now?

**Pull request merged**
