### PR TITLE
Pull request to support other seeds, like TheCore Lite

### PR DESCRIPTION
**Pull request by bobo38**
I modified TheCoreRemapper.py to support non-pure TheCore. This pull request contains my own version of TheCore Lite as an example. Warning : loads of things are flagged during the checks, I will have to work on this…

You could pull only those 2 files and regenerate the log and hotkeys yourself for verification:
- TheCoreRemapper.py
- TheCore Lite .SC2Hotkeys

If you requested, I could change the "TheCore Lite .SC2Hotkeys" seed (to remove flags) before the pull.

### CODE REVIEW

**Comment by bobo38** [comment]
I'm closing the pull request, because this version is outdated

**Comment by bobo38** [comment]
I have to find a way to make a pull request with minimal changes. This doesn't seem so easy.

I implemented:
- a clean support for others seeds than TheCore without dirty hack
- 4 additional checks
- a debug mode to tune TheCoreRemapper.py behaviour while modifying seeds
- a "remapHint" function that output keys that would generate conflicts + detailed conflict/key/command of potential conflict keys

You could find a detailed changelog of the code at the end of [my fork's README.md](https://github.com/bobo38/TheCoreConverter/blob/master/README.md). This is in the section called "Changelog for the code".

I have 3 versions of TheCore Lite, with slight [hotkeys] differences and same [commands], documented at the beginning of the same README.md.

**Comment by Hancho2009** [comment]
hey, you should join TheCore dev group on skype (ask Jak) - there are some drastic changes you did (include TheCore Lite in the Repo) - we have not disucssed how we want to handle the other TheCore layouts (atm I thiink splitting in multiple repos (TheCoreConverter, TheCore, TheCore+ and TheCore Lite) and use parameters for TheCoreConverter/Remapper script is a better way)
but you have some changes that I like for example the "make it executable under Linux" and that you use a dict in the Hotkey class for the keys instead of spereate variables for each key.
it would be cool to have you onboard

**Comment by bobo38** [comment]
Sure! Thanks for your email and interest. The code approach is quite
fun. I do love the GUI-less + text file inputs. The general spirit fits
with my "check | generate | revision control" approach.

I gave up installing Skype (some problem with my webcam running in
virtualbox) and got busy recently (kid stuff + end of parental leave).
Some guy found one of my Starcraft2 related  project, to tune the X
server generic keyboard driver and enable some rapid fire hotkeys under
Linux:
https://git.framasoft.org/bobo/xkb_repeat

I will try again the Skype stuff. Depending on your views, I could
split the changes I did for a pull request.

**Comment by Hancho2009** [comment]
- you can use https://web.skype.com/ - we only chat most of the time
- I just wanna make sure we dont block each other when we develope in diffrent directions
- I think the linux support i mentioned in my last post is fine and the other change too if it is not changing the log output (sort order)
- I think you added some stuff since last time I look at the pullrequest - i have not look too much on the new stuff
- if you create a pull request for the two things I will recommend to Jak to accept the request
- I am not that familiar with linux but thats sounds like a cool bugfix - does rapid fire work with wayland?

thanks for your engagement

**Comment by bobo38** [comment]
I joined the Skype discussion this afternoon

**Pull request closed without merging**
