### PR TITLE
Pullrequest

### PR DESCRIPTION
**Pull request by bobo38**
– Defaults.ini+ConflictChecks.py merge of old stuff with latest Sc2HotkeyData from Mads
– make DifferentDefault.ini consistent with new Defaults.ini
– remove inconsistencies in Same&Inheritance checks

### CODE REVIEW

**Comment by Hancho2009** [comment]
Maybe add in an other commit the script output so the log and generated layouts files match with the content

**Comment by bobo38** [comment]
Is it OK like this ?

After running the script:
– *.log are updated
– Defaults.ini is sorted alphabetically
– all defaults are added to */TheCore XYZ.SC2Hotkeys

I've pushed as well the header in TheCoreRemapper.py to make it executable by command line for Linux

**Comment by Hancho2009** [comment]
seems fine

**Comment by bobo38** [comment]
The idea is to use this script only for debug to:
- benefit from remap hints
- be able to ignore seeds you're not working on (seed or conflict contexts)
- get coverage for commands hotkeys on top of [Hotkeys] direct access key, i.e. control groups

TheCoreRemapper.py to be use before seed commit.

As a result, in Debug_settings.ini, debug mode is on, all TheCore Lite stuff is commented not to be taken into account, all XLM seeds are uncommented, generation desactivated, verbose and verydetail set to true, no conflict context is ignored.

Of course I could slightly modify it, to replace TheCoreRemapper.py

**Comment by bobo38** [comment]
This pull request is probably no longer relevant due to Mads' last commit

**Comment by BeedeBdoo** [comment]
I'd say it is relevant. New co-op commanders are going to be continued to be added (some of their data is present in the unit xml-files). + more segments of the Nova campaign. So there's still hotkeys to update in the future, and I believe this would be nice to have for that.

**Comment by BeedeBdoo** [comment]
Is there are way we can somehow merge this pull request and mine (given that JaK still hasn't accepted my pull request)?

**Comment by bobo38** [comment]
Once JaK will have merged your commit, I could re-make a pull request

**Comment by BeedeBdoo** [comment]
If that's easier for you, then sure

**Comment by Hancho2009** [comment]
bobo can pull beedebdoos in his own fork merge it there and than create a pull request to Jaks repo

**Comment by bobo38** [comment]
that's it

**Pull request closed without merging**
